#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then

    xrdb -merge $sysresources

fi


if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi


if [ -f "$userresources" ]; then

    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

xset -dpms
xset s off

xrandr --output DisplayPort-0 --set TearFree on &
xrandr --output DisplayPort-2 --set TearFree on &

xrandr --output DisplayPort-0 --mode 1920x1080 --rate 144
xrandr --output DisplayPort-2 --mode 1920x1080 --rate 144

XCURSOR_THEME="BreezeX-Light"
XCURSOR_SIZE="24"

export XDG_CURRENT_DESKTOP=i3
export DESKTOP_SESSION=i3
export XDG_MENU_PREFIX=i3-
export XDG_MENU_PREFIX=applications-

exec picom -b &
thunar --daemon &
xfce4-terminal --daemon &
feh --bg-scale ~/.config/wallpaper.svg &
eval "$(dbus-launch --sh-syntax --exit-with-session)" &
exec i3 > ~/.i3log 2>&1
